import os
import shlex
import stat
from typing import Optional, Tuple

import config
from home_paths import compute_home_directory
from ldap_core import logger


def create_home_directory(
    path: str, uid_number: int, gid_number: int, test_mode: bool = False
) -> Tuple[bool, str]:
    """Create home directory, chmod/chown to uid/gid."""
    path = (path or "").strip()
    if not path:
        return False, "Empty homeDirectory"

    if test_mode:
        return True, f"TEST_MODE: would create {path}"

    try:
        os.makedirs(path, exist_ok=True)
        mode = getattr(config, "HOME_DIR_MODE", stat.S_IRWXU)
        os.chmod(path, mode)
        os.chown(path, int(uid_number), int(gid_number))
        return True, f"Home directory ready: {path}"
    except Exception as e:
        return False, f"Home directory creation failed: {e}"


def _class_to_gid_and_home(username: str, class_key: str) -> Tuple[int, str]:
    """
    Backwards-compatible wrapper.

    Returns:
      (gid_number, home_directory)
    """
    return compute_home_directory(username, class_key)


def _append_zimbra_command(
    username: str,
    given_name: str,
    family_name: str,
    class_key: str,
    password: str,
    display_name: Optional[str] = None,
    admin_user: str = "",
) -> None:
    """
    Append a Zimbra 'zmprov ca' command to the provision script.
    Only runs if ZIMBRA_STUDENT_SCRIPY is set and we're NOT in test_mode.
    WARNING: This writes plaintext passwords to a script file.
    """

    student_script_path = getattr(config, "ZIMBRA_STUDENT_SCRIPT", None)
    if not student_script_path:
        return  # feature disabled
    staff_script_path = getattr(config, "ZIMBRA_STAFF_SCRIPT", None)
    if not staff_script_path:
        return  # feature disabled

    script_path = ""
    # Staff vs student domain
    if class_key == "Staff":
        domain = getattr(config, "ZIMBRA_STAFF_DOMAIN", "lorien.nsw.edu.au")
        script_path = staff_script_path
    else:
        domain = getattr(config, "ZIMBRA_STUDENT_DOMAIN", "students.lorien.nsw.edu.au")
        script_path = student_script_path

    email = f"{username}@{domain}"

    disp = display_name or f"{given_name} {family_name}"
    admin_user = admin_user or "unknown"

    # Safe-ish shell quoting
    def q(x: str) -> str:
        return shlex.quote(x)

    line = (
        f"zmprov ca {q(email)} {q(password)} "
        f"displayName {q(disp)} givenName {q(given_name)} sn {q(family_name)} "
        f"# created_by={q(admin_user)}\n"
    )

    # Ensure script exists and has shebang on first write
    try:
        new_file = not os.path.exists(script_path)
        with open(script_path, "a", encoding="utf-8") as f:
            if new_file:
                f.write("#!/bin/bash\n")
                f.write("# Zimbra account provisioning script generated by ldap_admin_flask\n\n")
            f.write(line)
        # Make it executable
        try:
            st = os.stat(script_path)
            os.chmod(script_path, st.st_mode | 0o111)  # add +x
        except Exception:
            pass
    except Exception as e:
        logger.error("Failed to append Zimbra command: %s", e)
